name: ATC Live Agent
on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes to stay within free API limits
  workflow_dispatch:

jobs:
  run-radar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install requests numpy
      - run: python app.py
      - name: Deploy Data
        run: |
          git config --global user.name "ATC-Agent"
          git config --global user.email "atc@agent.ai"
          git add data.json
          git commit -m "Live Radar Update" || exit 0
          git push
